apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rust-wasm-service
  namespace: default
spec:
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat-smart
    spec:
      containers:
        - name: rust-wasm-service
          image: ghcr.io/tscng/wasmedge-rust-knative-plugin-demo
          ports:
            - containerPort: 8080
          env:
            - name: WASMEDGE_PLUGIN_PATH
              value: "/plugin"
          volumeMounts:
            - name: plugin-volume
              mountPath: /plugin

      volumes:
        - name: plugin-volume
          configMap:
            name: wasmedge-plugins